import unittest

from canlogconvert.traces.formats.trc import load_string
from canlogconvert.traces.formats.internal_trace import InternalMessageDirection


class TrcTest(unittest.TestCase):
    def test_load_string_supported_version_2_1(self):
        # We currently only support File Version 2.1
        input_string = """\
;$FILEVERSION=2.1
;$STARTTIME=43474.7738065227
;$COLUMNS=N,O,T,B,I,d,R,L,D
;
;   C:\Temp\2019-01-09_18-34-16_844.trc
;   Start time: 2019-01-09 18:34:16.883.5
;   Generated by PCAN-Explorer v6.2.1.1946
;-------------------------------------------------------------------------------
;   Bus  Connection   Net Connection     Protocol  Bit rate
;   1    Connection1  Untitled@pcan_usb  CAN       500 kBit/s
;-------------------------------------------------------------------------------
;   Message    Time    Type    ID     Rx/Tx
;   Number     Offset  |  Bus  [hex]  |  Reserved
;   |          [ms]    |  |    |      |  |  Data Length Code
;   |          |       |  |    |      |  |  |    Data [hex] ...
;   |          |       |  |    |      |  |  |    |
;---+--- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --
       1        39.488 DT 1      0401 Rx -  6    0A 00 66 98 0B 00
        """

        db = load_string(input_string)
        self.assertIsNotNone(db.messages)
        self.assertEqual(len(db.messages), 1)
        self.assertEqual(db.messages[0].arbitration_id, 0x0401)
        self.assertEqual(
            db.messages[0].data, bytearray([0x0A, 0x00, 0x66, 0x98, 0x0B, 0x00])
        )
        self.assertEqual(db.messages[0].dlc, 6)
        self.assertEqual(db.messages[0].direction, InternalMessageDirection.RX)

    def test_load_string_unsupported_version_1_1(self):
        # We currently only support File Version 2.1
        input_string = """\
;$FILEVERSION=1.1
;$STARTTIME=43474.7738065227
;$COLUMNS=N,O,T,B,I,d,R,L,D
;
;   C:\Temp\2019-01-09_18-34-16_844.trc
;   Start time: 2019-01-09 18:34:16.883.5
;   Generated by PCAN-Explorer v6.2.1.1946
;-------------------------------------------------------------------------------
;   Bus  Connection   Net Connection     Protocol  Bit rate
;   1    Connection1  Untitled@pcan_usb  CAN       500 kBit/s
;-------------------------------------------------------------------------------
;   Message    Time    Type    ID     Rx/Tx
;   Number     Offset  |  Bus  [hex]  |  Reserved
;   |          [ms]    |  |    |      |  |  Data Length Code
;   |          |       |  |    |      |  |  |    Data [hex] ...
;   |          |       |  |    |      |  |  |    |
;---+--- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --
       1        39.488 DT 1      0401 Rx -  6    0A 00 66 98 0B 00
        """

        self.assertRaises(ValueError, load_string, input_string)


if __name__ == "__main__":
    unittest.main()
